version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${SERVICE_VERSION_UI}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${SERVICE_VERSION_POST}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${SERVICE_VERSION_COMMENT}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
