version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${SERVICE_VERSION_UI}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${SERVICE_VERSION_POST}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${SERVICE_VERSION_COMMENT}
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
